// Copyright (C) 2018 Sebastian Lühnen
//
//
// This file is part of NerdyUserInputEmulator.
// 
// NerdyUserInputEmulator is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// NerdyUserInputEmulator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with NerdyUserInputEmulator. If not, see <http://www.gnu.org/licenses/>.
//
//
// Created By: Sebastian Lühnen
// Created On: 30.06.2018
// Last Edited On: 13.07.2018
// Language: C#
//
using System;
using System.Runtime.InteropServices;

namespace SCHREDDO.Nerdy.UserInput.Emulator.Enums
{
    public enum KeyName
    {
        L_BUTTON,
        R_BUTTON,
        CANCEL,
        M_BUTTON,
        X_BUTTON_1,
        X_BUTTON_2,
        BACK,
        TAB,
        CLEAR,
        RETURN,
        SHIFT,
        CONTROL,
        MENU,
        PAUSE,
        CAPITAL,
        KANA,
        HANGUEL,
        HANGUL,
        JUNJA,
        FINAL,
        HANJA,
        KANJI,
        ESCAPE,
        CONVERT,
        NONCONVERT,
        ACCEPT,
        MODECHANGE,
        SPACE,
        PRIOR,
        NEXT,
        END,
        HOME,
        LEFT,
        UP,
        RIGHT,
        DOWN,
        SELECT,
        PRINT,
        EXECUTE,
        SNAPSHOT,
        INSERT,
        DELETE,
        HELP,
        KEY_0,
        KEY_1,
        KEY_2,
        KEY_3,
        KEY_4,
        KEY_5,
        KEY_6,
        KEY_7,
        KEY_8,
        KEY_9,
        KEY_A,
        KEY_B,
        KEY_C,
        KEY_D,
        KEY_E,
        KEY_F,
        KEY_G,
        KEY_H,
        KEY_I,
        KEY_J,
        KEY_K,
        KEY_L,
        KEY_M,
        KEY_N,
        KEY_O,
        KEY_P,
        KEY_Q,
        KEY_R,
        KEY_S,
        KEY_T,
        KEY_U,
        KEY_V,
        KEY_W,
        KEY_X,
        KEY_Y,
        KEY_Z,
        LWIN,
        RWIN,
        APPS,
        SLEEP,
        NUMPAD0,
        NUMPAD1,
        NUMPAD2,
        NUMPAD3,
        NUMPAD4,
        NUMPAD5,
        NUMPAD6,
        NUMPAD7,
        NUMPAD8,
        NUMPAD9,
        MULTIPLY,
        ADD,
        SEPARATOR,
        SUBTRACT,
        DECIMAL,
        DIVIDE,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        NUMLOCK,
        SCROLL,
        LSHIFT,
        RSHIFT,
        LCONTROL,
        RCONTROL,
        LMENU,
        RMENU,
        BROWSER_BACK,
        BROWSER_FORWARD,
        BROWSER_REFRESH,
        BROWSER_STOP,
        BROWSER_SEARCH,
        BROWSER_FAVORITES,
        BROWSER_HOME,
        VOLUME_MUTE,
        VOLUME_DOWN,
        VOLUME_UP,
        MEDIA_NEXT_TRACK,
        MEDIA_PREV_TRACK,
        MEDIA_STOP,
        MEDIA_PLAY_PAUSE,
        LAUNCH_MAIL,
        LAUNCH_MEDIA_SELECT,
        LAUNCH_APP1,
        LAUNCH_APP2,
        OEM_1,
        OEM_PLUS,
        OEM_COMMA,
        OEM_MINUS,
        OEM_PERIOD,
        OEM_2,
        OEM_3,
        OEM_4,
        OEM_5,
        OEM_6,
        OEM_7,
        OEM_8,
        OEM_102,
        PROCESSKEY,
        PACKET,
        ATTN,
        CRSEL,
        EXSEL,
        EREOF,
        PLAY,
        ZOOM,
        NONAME,
        PA1,
        OEM_CLEAR
    }
}
